#!/bin/env bash

if [[ ! -f ${OPENSHIFT_DATA_DIR}/.deployed ]]; then
    mysql --user=${OPENSHIFT_MYSQL_DB_USERNAME} --password=${OPENSHIFT_MYSQL_DB_PASSWORD} --host=${OPENSHIFT_MYSQL_DB_HOST} --port=${OPENSHIFT_MYSQL_DB_PORT} ${OPENSHIFT_APP_NAME} < ${OPENSHIFT_REPO_DIR}.openshift/modx.sql
    touch ${OPENSHIFT_DATA_DIR}/.deployed
fi
